#!/bin/sh

echo "" >> /usr/lib/lua/luci/view/footer.htm
echo "" >> /usr/lib/lua/luci/view/footer.htm
echo '<link rel="stylesheet" href="/live2d/font-awesome.min.css"/>' >> /usr/lib/lua/luci/view/footer.htm
echo '<script src="/live2d/autoload.js"></script>' >> /usr/lib/lua/luci/view/footer.htm


exit 0
